use crate::error::Result;
use crate::git::service::GitService;
use std::path::Path;

/// Structured finding from code review
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct ReviewFinding {
    pub category: String,
    pub severity: String, // "HIGH", "MEDIUM", "LOW", "PASS"
    pub title: String,
    pub details: String,
    pub line_hint: Option<String>,
}

/// Scorecard and audit report generated by the code reviewer
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct ReviewReport {
    pub total_score: u32,
    pub files_audited: usize,
    pub findings: Vec<ReviewFinding>,
    pub summary: String,
}

/// Multi-dimensional code review engine evaluating git changes across 5 critical pillars.
pub struct GitReviewer;

impl GitReviewer {
    /// Audits uncommitted or staged changes in the workspace and produces a markdown review scorecard.
    pub async fn review_workspace(
        workspace_root: &Path,
        staged_only: bool,
    ) -> Result<ReviewReport> {
        let git = GitService::new(workspace_root.to_path_buf());
        if !git.is_git_repo().await {
            return Ok(ReviewReport {
                total_score: 100,
                files_audited: 0,
                findings: vec![],
                summary: "ℹ Workspace is not a git repository.".to_string(),
            });
        }

        let diff_text = git.diff(staged_only, None).await?;
        let status = git.get_status().await?;

        let target_files = if staged_only {
            status.staged
        } else {
            let mut all = status.staged;
            all.extend(status.unstaged);
            all.sort();
            all.dedup();
            all
        };

        if target_files.is_empty() && diff_text.trim().is_empty() {
            return Ok(ReviewReport {
                total_score: 100,
                files_audited: 0,
                findings: vec![],
                summary: "✔ Working tree is completely clean — zero uncommitted diffs to audit."
                    .to_string(),
            });
        }

        let mut findings = Vec::new();
        let mut score = 100_u32;

        // 1. Secret & Sensitive Data Audit
        for line in diff_text.lines() {
            if line.starts_with('+') && !line.starts_with("+++") {
                let added = &line[1..].trim();
                if (added.contains("api_key")
                    || added.contains("secret")
                    || added.contains("password")
                    || added.contains("token"))
                    && (added.contains("=") || added.contains(":"))
                    && !added.contains("env::")
                    && !added.contains("process.env")
                    && !added.contains("std::env")
                {
                    findings.push(ReviewFinding {
                        category: "Security & Secret Leakage".to_string(),
                        severity: "HIGH".to_string(),
                        title: "Potential Hardcoded Secret / Credential".to_string(),
                        details: format!(
                            "Added line contains sensitive keyword assignment: `{}`",
                            added
                        ),
                        line_hint: Some(line.to_string()),
                    });
                    score = score.saturating_sub(25);
                }

                // 2. Unsafe / Panic Patterns (for Rust code)
                if added.contains(".unwrap()") || added.contains(".expect(") {
                    findings.push(ReviewFinding {
                        category: "Correctness & Invariant Safety".to_string(),
                        severity: "MEDIUM".to_string(),
                        title: "Explicit Panic / Unwrap Pattern".to_string(),
                        details: format!("Prefer proper `?` error propagation with `thiserror`/`anyhow` instead of `.unwrap()`: `{}`", added),
                        line_hint: Some(line.to_string()),
                    });
                    score = score.saturating_sub(10);
                }

                // 3. Debug logging in library code
                if added.contains("println!")
                    || added.contains("eprintln!")
                    || added.contains("console.log")
                {
                    findings.push(ReviewFinding {
                        category: "Architecture & Observability".to_string(),
                        severity: "LOW".to_string(),
                        title: "Stdout Debug Statement".to_string(),
                        details: format!("Use structured logging (`tracing::debug!`, `tracing::info!`) instead of raw stdout: `{}`", added),
                        line_hint: Some(line.to_string()),
                    });
                    score = score.saturating_sub(5);
                }
            }
        }

        // 4. Missing Tests Check
        let has_code_changes = target_files
            .iter()
            .any(|f| f.ends_with(".rs") || f.ends_with(".ts") || f.ends_with(".py"));
        let has_test_changes = target_files
            .iter()
            .any(|f| f.contains("test") || f.contains("spec"));

        if has_code_changes && !has_test_changes {
            findings.push(ReviewFinding {
                category: "Verification & Test Coverage".to_string(),
                severity: "MEDIUM".to_string(),
                title: "Code Changes Detected Without Associated Tests".to_string(),
                details:
                    "Source code was modified without additions in `tests/` or unit test blocks."
                        .to_string(),
                line_hint: None,
            });
            score = score.saturating_sub(15);
        }

        // 5. Structural & Public API Impact Analysis (DiffProjector)
        if let Ok(projection) = crate::git::diff_projector::DiffProjector::project_workspace_diff(
            workspace_root,
            staged_only,
            None,
        )
        .await
        {
            for b in projection.breaking_changes {
                findings.push(ReviewFinding {
                    category: "Structural & Public API Impact".to_string(),
                    severity: "HIGH".to_string(),
                    title: format!("Breaking API Change in `{}`", b.symbol_name),
                    details: b.breaking_reason.unwrap_or_else(|| {
                        format!(
                            "Public symbol `{}` in `{}` modified (affects {} callers)",
                            b.symbol_name,
                            b.file_path,
                            b.direct_callers.len()
                        )
                    }),
                    line_hint: Some(format!("lines {}-{}", b.start_line, b.end_line)),
                });
                score = score.saturating_sub(20);
            }

            for h in projection.high_risk_symbols {
                if !h.is_breaking && h.pagerank_score > 0.04 {
                    findings.push(ReviewFinding {
                        category: "Architectural Risk & Blast Radius".to_string(),
                        severity: "MEDIUM".to_string(),
                        title: format!("High-Centrality Symbol Modified: `{}`", h.symbol_name),
                        details: format!(
                            "Symbol has PageRank score {:.4} and {} direct incoming callers.",
                            h.pagerank_score,
                            h.direct_callers.len()
                        ),
                        line_hint: Some(format!(
                            "{}:lines {}-{}",
                            h.file_path, h.start_line, h.end_line
                        )),
                    });
                    score = score.saturating_sub(10);
                }
            }
        }

        // 6. AST Code Smells & Complexity Anti-Patterns
        for f in &target_files {
            if let Ok(smell_report) =
                crate::context::smell_detector::AstSmellDetector::scan_workspace(
                    workspace_root,
                    None,
                    Some(f),
                )
            {
                for smell in smell_report.smells {
                    findings.push(ReviewFinding {
                        category: "AST Code Health & Antipatterns".to_string(),
                        severity: smell.severity,
                        title: format!("{}: {}", smell.category.badge(), smell.message),
                        details: smell.remediation,
                        line_hint: Some(format!(
                            "{}:lines {}-{}",
                            smell.file_path, smell.start_line, smell.end_line
                        )),
                    });
                    score = score.saturating_sub(5);
                }
            }
        }

        let summary = format!(
            "🛡️ **Multi-Agent Code Review Scorecard**\n\n\
            • **Overall Quality Score:** {} / 100\n\
            • **Files Evaluated:** {} file(s)\n\
            • **Total Findings:** {} ({} High, {} Medium, {} Low)\n",
            score,
            target_files.len(),
            findings.len(),
            findings.iter().filter(|f| f.severity == "HIGH").count(),
            findings.iter().filter(|f| f.severity == "MEDIUM").count(),
            findings.iter().filter(|f| f.severity == "LOW").count()
        );

        Ok(ReviewReport {
            total_score: score,
            files_audited: target_files.len(),
            findings,
            summary,
        })
    }

    /// Formats the review report into an interactive markdown string.
    pub fn format_report(report: &ReviewReport) -> String {
        let mut out = report.summary.clone();

        if report.findings.is_empty() {
            out.push_str("\n✨ **All checks passed cleanly!** No architectural defects, secret leaks, or logic risks found.\n");
            return out;
        }

        out.push_str("\n### Detailed Findings:\n\n");
        for (i, f) in report.findings.iter().enumerate() {
            let badge = match f.severity.as_str() {
                "HIGH" => "🔴 [HIGH]",
                "MEDIUM" => "🟡 [MEDIUM]",
                _ => "🔵 [LOW]",
            };

            out.push_str(&format!(
                "{}. {} **{}** ({})\n   • **Issue:** {}\n",
                i + 1,
                badge,
                f.title,
                f.category,
                f.details
            ));
            if let Some(ref hint) = f.line_hint {
                out.push_str(&format!("   • **Snippet:** `{}`\n", hint.trim()));
            }
            out.push('\n');
        }

        out
    }
}
