use crate::error::Result;
use crate::lsp::diagnostics::FastCompilerChecker;
use crate::sandbox::redact::SecretRedactor;
use serde::{Deserialize, Serialize};
use std::path::Path;

/// Severity level of a Critic finding
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum IssueSeverity {
    Critical,
    Warning,
    Info,
}

impl IssueSeverity {
    pub fn badge(&self) -> &'static str {
        match self {
            IssueSeverity::Critical => "[CRITICAL]",
            IssueSeverity::Warning => "[WARNING]",
            IssueSeverity::Info => "[INFO]",
        }
    }
}

/// An individual finding identified by the Critic verification pass
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct CriticIssue {
    pub category: String,
    pub severity: IssueSeverity,
    pub file_path: Option<String>,
    pub line_number: Option<usize>,
    pub description: String,
    pub recommendation: String,
}

/// Overall verdict from an automated Critic review
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum CriticVerdict {
    Approved,
    ApprovedWithWarnings,
    Rejected,
}

impl CriticVerdict {
    pub fn is_approved(&self) -> bool {
        matches!(
            self,
            CriticVerdict::Approved | CriticVerdict::ApprovedWithWarnings
        )
    }

    pub fn status_text(&self) -> &'static str {
        match self {
            CriticVerdict::Approved => "✔ Approved (Clean)",
            CriticVerdict::ApprovedWithWarnings => "✔ Approved (with non-blocking warnings)",
            CriticVerdict::Rejected => "✗ Rejected (Blocking errors found)",
        }
    }
}

/// Comprehensive report generated by the Actor-Critic verification engine
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct CriticReport {
    pub verdict: CriticVerdict,
    pub is_approved: bool,
    pub compiler_clean: bool,
    pub conventions_clean: bool,
    pub security_clean: bool,
    pub compiler_errors: usize,
    pub compiler_warnings: usize,
    pub uncommitted_files: Vec<String>,
    pub issues: Vec<CriticIssue>,
    pub summary: String,
}

impl CriticReport {
    /// Formats the report into a clean, actionable Markdown message for the agent loop
    pub fn format_for_agent(&self) -> String {
        let mut out = format!(
            "### Critic Verification: {}\n\n",
            self.verdict.status_text()
        );

        out.push_str(&format!(
            "• Compiler Diagnostics: {}\n• Coding Conventions: {}\n• Security & Secrets: {}\n• Modified Files: {}\n\n",
            if self.compiler_clean { "✔ Clean" } else { "✗ Errors Detected" },
            if self.conventions_clean { "✔ Compliant" } else { "⚠ Issues Found" },
            if self.security_clean { "✔ Secure" } else { "✗ Potential Secrets" },
            self.uncommitted_files.len()
        ));

        if !self.issues.is_empty() {
            out.push_str("#### Identified Findings & Feedback:\n");
            for (idx, issue) in self.issues.iter().enumerate() {
                let loc = if let Some(ref path) = issue.file_path {
                    if let Some(line) = issue.line_number {
                        format!(" (`{}:{}`)", path, line)
                    } else {
                        format!(" (`{}`)", path)
                    }
                } else {
                    String::new()
                };

                out.push_str(&format!(
                    "{}. **{}** `{}`{}: {}\n   _Action:_ {}\n",
                    idx + 1,
                    issue.severity.badge(),
                    issue.category,
                    loc,
                    issue.description,
                    issue.recommendation
                ));
            }
        } else {
            out.push_str(
                "Zero defects detected across compiler, convention, and security checks.\n",
            );
        }

        out
    }
}

/// High-precision Actor-Critic verification engine
pub struct CriticValidator;

impl CriticValidator {
    /// Runs a multi-dimensional verification pass across compiler diagnostics, conventions, and security
    pub async fn review_workspace(workspace_root: &Path) -> Result<CriticReport> {
        let mut issues = Vec::new();
        let mut compiler_errors = 0;
        let mut compiler_warnings = 0;

        // 1. Check Compiler Diagnostics via LSP / Cargo Check
        let compiler_clean = match FastCompilerChecker::check_workspace(workspace_root).await {
            Ok(report) => {
                compiler_errors = report.errors.len();
                compiler_warnings = report.warnings.len();

                for err in &report.errors {
                    issues.push(CriticIssue {
                        category: "compiler_error".to_string(),
                        severity: IssueSeverity::Critical,
                        file_path: Some(err.file.to_string_lossy().to_string()),
                        line_number: Some(err.line),
                        description: err.message.clone(),
                        recommendation: "Fix compiler diagnostic error to maintain build integrity.".to_string(),
                    });
                }

                for warn in &report.warnings {
                    issues.push(CriticIssue {
                        category: "compiler_warning".to_string(),
                        severity: IssueSeverity::Warning,
                        file_path: Some(warn.file.to_string_lossy().to_string()),
                        line_number: Some(warn.line),
                        description: warn.message.clone(),
                        recommendation: "Consider resolving compiler warning for clean build."
                            .to_string(),
                    });
                }

                report.is_clean()
            }
            Err(_) => true,
        };

        // 2. Query Git status for modified files
        let uncommitted_files = Self::get_modified_files(workspace_root).await;

        // 3. Scan modified files for anti-patterns and security issues
        let (conventions_clean, security_clean) =
            Self::scan_modified_files(workspace_root, &uncommitted_files, &mut issues).await;

        // 4. Formulate Verdict
        let has_critical = issues.iter().any(|i| i.severity == IssueSeverity::Critical);
        let has_warnings = issues.iter().any(|i| i.severity == IssueSeverity::Warning);

        let verdict = if has_critical {
            CriticVerdict::Rejected
        } else if has_warnings {
            CriticVerdict::ApprovedWithWarnings
        } else {
            CriticVerdict::Approved
        };

        let is_approved = verdict.is_approved();
        let summary = format!(
            "Critic evaluated {} modified files: {} critical issues, {} warnings",
            uncommitted_files.len(),
            issues
                .iter()
                .filter(|i| i.severity == IssueSeverity::Critical)
                .count(),
            issues
                .iter()
                .filter(|i| i.severity == IssueSeverity::Warning)
                .count()
        );

        Ok(CriticReport {
            verdict,
            is_approved,
            compiler_clean,
            conventions_clean,
            security_clean,
            compiler_errors,
            compiler_warnings,
            uncommitted_files,
            issues,
            summary,
        })
    }

    /// Retrieves list of modified and untracked files via Git
    async fn get_modified_files(workspace_root: &Path) -> Vec<String> {
        let mut files = Vec::new();
        if let Ok(output) = tokio::process::Command::new("git")
            .args(["status", "--short"])
            .current_dir(workspace_root)
            .output()
            .await
        {
            if output.status.success() {
                let status_str = String::from_utf8_lossy(&output.stdout);
                for line in status_str.lines() {
                    let trimmed = line.trim();
                    if trimmed.len() > 3 {
                        let path_part = &trimmed[3..].trim();
                        files.push(path_part.to_string());
                    }
                }
            }
        }
        files
    }

    /// Scans source files for anti-patterns and secret leaks
    async fn scan_modified_files(
        workspace_root: &Path,
        files: &[String],
        issues: &mut Vec<CriticIssue>,
    ) -> (bool, bool) {
        let mut conventions_clean = true;
        let mut security_clean = true;
        let redactor = SecretRedactor::global();

        for file_rel in files {
            // Only inspect source files (skip lockfiles, binaries, images)
            if file_rel.ends_with(".lock")
                || file_rel.ends_with(".png")
                || file_rel.ends_with(".jpg")
                || file_rel.ends_with(".wasm")
            {
                continue;
            }

            let full_path = workspace_root.join(file_rel);
            if let Ok(content) = tokio::fs::read_to_string(&full_path).await {
                // Check for secret leaks
                if redactor.redact(&content) != content {
                    security_clean = false;
                    issues.push(CriticIssue {
                        category: "security_secret_leak".to_string(),
                        severity: IssueSeverity::Critical,
                        file_path: Some(file_rel.clone()),
                        line_number: None,
                        description:
                            "File contains unredacted API key, bearer token, or secret pattern."
                                .to_string(),
                        recommendation:
                            "Remove or mask hardcoded secrets before saving or committing."
                                .to_string(),
                    });
                }

                // Check Rust-specific conventions if applicable
                if file_rel.ends_with(".rs") && !file_rel.starts_with("tests/") {
                    for (line_idx, line) in content.lines().enumerate() {
                        let line_no = line_idx + 1;
                        let trimmed = line.trim();

                        // Anti-pattern: raw println! / eprintln! in non-test library code
                        if (trimmed.starts_with("println!(") || trimmed.starts_with("eprintln!("))
                            && !file_rel.starts_with("src/main.rs")
                            && !file_rel.starts_with("benches/")
                        {
                            conventions_clean = false;
                            issues.push(CriticIssue {
                                category: "convention_logging".to_string(),
                                severity: IssueSeverity::Warning,
                                file_path: Some(file_rel.clone()),
                                line_number: Some(line_no),
                                description: "Use `tracing::info!` or `tracing::debug!` instead of `println!` in library modules.".to_string(),
                                recommendation: "Replace with structured tracing macro to preserve terminal UI integrity.".to_string(),
                            });
                        }
                    }
                }
            }
        }

        (conventions_clean, security_clean)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::tempdir;

    #[tokio::test]
    async fn test_critic_review_clean_directory() {
        let dir = tempdir().unwrap();
        let report = CriticValidator::review_workspace(dir.path()).await.unwrap();
        assert!(report.is_approved);
        assert_eq!(report.compiler_errors, 0);
        assert!(report.compiler_clean);
        assert!(report.conventions_clean);
        assert!(report.security_clean);
    }

    #[tokio::test]
    async fn test_critic_report_formatting() {
        let report = CriticReport {
            verdict: CriticVerdict::Approved,
            is_approved: true,
            compiler_clean: true,
            conventions_clean: true,
            security_clean: true,
            compiler_errors: 0,
            compiler_warnings: 0,
            uncommitted_files: vec!["src/lib.rs".to_string()],
            issues: Vec::new(),
            summary: "All clean".to_string(),
        };

        let formatted = report.format_for_agent();
        assert!(formatted.contains("Critic Verification"));
        assert!(formatted.contains("Zero defects detected"));
    }
}
