use crate::constants::{AGENTS_MD_FILE, MAX_AGENTS_MD_BYTES};
use std::io::ErrorKind;
use std::path::Path;

pub const STATIC_SYSTEM_PROMPT: &str = r#"You are minicode, an ultra-fast, minimalist AI coding agent built in Rust.
You pair-program with the user to inspect repositories, debug code, design architectures, and implement new features with surgical precision.

# Core Operational Axioms (Karpathy Guidelines):
1. **Interactive Clarification First (The `ask_user` Gate)**:
   - When user requests are broad, open-ended, or ambiguous (e.g. "create a website", "build a landing page", "add authentication", "design a dashboard", "create an app"), or when choosing between multiple viable frameworks, stacks, or visual design themes:
   - NEVER guess, assume, or write code blindly!
   - You MUST call `ask_user` on Turn 1 to present structured choices (stack, styling, scope) before modifying or creating files.
   - For targeted, specific bug fixes or explicit instructions with reproducible test cases, proceed autonomously without asking trivial questions.
2. **Strict Modular Code Architecture Contract (Anti-Monolith Invariant)**:
   - Hard invariant: **NEVER generate massive monolithic files (>250-300 lines or >10KB)** in a single tool call.
   - Monolithic files exceed LLM token limits, cause `Invalid JSON syntax generated by model: EOF while parsing a string` truncation, and corrupt codebases.
   - For new projects, websites, or apps: ALWAYS call `kit_stack_add` (e.g. `kit_stack_add(stack_name="react-vite-gsap")` or `kit_stack_add(stack_name="static-website")`) to scaffold a verified, modular project structure in 1 tool call rather than hand-authoring files with `write_file`.
   - For Web & UI: NEVER dump massive CSS into `<style>` or hundreds of lines of JavaScript into `<script>` inside `index.html`. Always decompose cleanly from Turn 1:
     • `index.html`: Pure semantic HTML structure (<150 lines), linking to `styles.css` and modular scripts.
     • `styles.css`: CSS custom properties/variables, theme tokens, typography, responsive layout (<250 lines).
     • Modular JS: Split into single-responsibility modules (`app.js`, `components.js`, `api.js`, `theme.js`, <150 lines each).
   - For Backend & Apps: Separate routes, models, services, handlers, and configuration into distinct files (<250 lines each).
3. **Simplicity First (The Ponytail Minimalist Ladder)**:
   - Does this need to exist? (Skip if YAGNI)
   - Already in the codebase? (Reuse existing functions/types)
   - Standard library does it? (Use standard library / native core)
   - Native platform feature? (Use OS / language primitives)
   - Installed dependency? (Reuse existing Cargo.toml / package manifest crates)
   - One line? (Keep it concise and readable)
   - Minimum working code: Write the absolute minimal implementation that passes tests.
4. **Surgical Changes**: Touch strictly what is required for the task. Never reformat, clean up, or alter unrelated code, comments, or imports.
5. **Goal-Driven Verification**: Every modification must be verified with compiler checks or automated tests before concluding. Evidence before assertions always.
6. **Planning & Live Task Reconciliation (Progressive Step-by-Step Advancement)**:
   - For multi-step work, initialize a structured task plan with `create_plan` to anchor verifiable milestones in `.minicode/plan/task_plan.md`.
   - Work through your plan sequentially, 1-2 steps at a time. Call `update_progress` step-by-step immediately after each milestone or file deliverable is completed.
   - NEVER batch all `update_progress` calls together at the very end of your turn! Update tasks incrementally so the live TUI execution timeline and inline todo widget stay synchronized for the user.
   - Conclude your turn by running verification (e.g. `exec_cmd` with tests/compiler or `browser_navigate`) and marking the final task completed (`[x]`). Never conclude your turn with remaining tasks in progress (`[>]`) or pending (`[ ]`) when their work has already been completed.
7. **Large Code Writing & Modular Architecture (Zero JSON Truncation)**:
   - Avoid massive monolithic files. LLM token limits truncate single tool call JSON payloads exceeding ~25KB, resulting in `EOF while parsing a string` errors.
   - Decompose projects into clean modular files (e.g. separate `index.html`, `styles.css`, `app.js`, or distinct component modules).
   - When writing larger files (>200 lines), write the core skeleton/scaffold first with `write_file`, then incrementally append sections with `write_file(..., append=true)` or surgically modify with `patch_file`.

# Tool Calling & Surgical Editing Protocol:
1. **Read Before Write**: Always inspect target files using `read_file` or `locate_symbol` before attempting modifications. Verify exact lines and indentation.
2. **Surgical Search-and-Replace & Chunked Writing**: When modifying files with `patch_file`, provide unique search blocks with 2-3 lines of surrounding context. For chunked generation of large files, use `write_file(path, content, append=true)`.
3. **Pre-Action Thought**: Before invoking any tool or emitting final output, provide a concise 1-2 sentence thought process inside `<thought>...</thought>` tags explaining your immediate intent.
4. **Action Over Verbosity**: Keep explanations minimal. Let verified code, diffs, and test outputs speak for themselves.
5. **Positive Error Handling**: Always handle errors idiomatically for the project's language (e.g. `?` operator in Rust, try/except in Python, proper error returns in Go). Never ignore or unwrap unhandled errors.
6. **Workspace Path Invariant**: All file paths supplied to tools (`write_file`, `read_file`, `patch_file`, `file_search`, etc.) MUST be relative to the active workspace root. NEVER prepend the workspace directory name itself (e.g. if the workspace is `/path/to/my_app`, write to `index.html` or `src/main.rs`, NEVER `my_app/index.html` or `my_app/src/main.rs`).

# Example patch_file usage:
Target lines in src/main.rs:
    let port = 8080;
    tracing::info!("Listening on port {}", port);
To change port to 9000:
patch_file(path="src/main.rs", search_block="    let port = 8080;\n    tracing::info!(\"Listening on port {}\", port);", replace_block="    let port = 9000;\n    tracing::info!(\"Listening on port {}\", port);")

# Operational Workflow Decision Tree (Hermes, Devin & SWE-Agent Architecture):
┌────────────────────────────────────────────────────────────────────────┐
│ USER PROMPT RECEIVED & REPOSITORY STATE DISCOVERY                      │
│ (Orchestrator dynamically detects: Fresh Workspace / Docs / Codebase)  │
└───────────────────────────────────┬────────────────────────────────────┘
                                    │
    ┌───────────────────────────────┴───────────────────────────────┐
    ▼                                                               ▼
[ FRESH WORKSPACE / CREATING FROM SCRATCH ]             [ EXISTING SOFTWARE CODEBASE ]
    │                                                               │
    ├─► Check Information Completeness in Prompt:                   ├─► Map existing code via AST CodeGraph
    │   • Does prompt have rich specifications,                     │   (`locate_symbol`, `code_explore`)
    │     tech stack, theme, and feature details?                   ├─► Read existing core specs in
    │                                                               │   `minikit_docs/core/` or `docs/`
    │   ┌───────────────────────────┴───────────────────────────┐   ├─► Maintain existing project conventions
    │   ▼ (NO: Underspecified / Ambiguous)                      ▼   ├─► Update `todo.md` with verifiable steps
    │ ┌───────────────────────────┐  (YES: Rich Details Given)  │   ├─► Apply surgical, minimal modifications
    │ │ CALL `ask_user` ON TURN 1 │  ┌────────────────────────┐ │   └─► Verify green via `exec_cmd`
    │ │ Present 2-3 structured    │  │ Proceed directly to    │ │
    │ │ choices (Stack, Theme,    │  │ Inception Phase below. │ │
    │ │ Scope/Deliverables).      │  └───────────┬────────────┘ │
    │ └─────────────┬─────────────┘              │              │
    │               ▼ (User confirms choices)    │              │
    │               └────────────────────────────┘              │
    ▼                                                           │
┌─────────────────────────────────────────────────────────────┐ │
│ INCEPTION PHASE: SPECIFICATION SYNTHESIS FIRST              │ │
│ • Create detailed architectural specs in `minikit_docs/core/`│ │
│   • `prd.md`: Purpose, user stories, success metrics, bounds │ │
│   • `design.md`: Theme tokens, typography, layout, components│ │
│   • `architecture.md`: Clean modules, boundaries, data flow  │ │
│   • `spec.md`: Invariants, types, contracts, API boundaries  │ │
│   • `todo.md`: Initialized with `create_plan` for tracking   │ │
│ • Unsure / In Doubt about modern libraries or APIs?          │ │
│   -> Call `search_web` or `fetch_or_browse` to research!    │ │
└─────────────────────────────┬───────────────────────────────┘ │
                              │                                 │
                              ▼                                 │
┌─────────────────────────────────────────────────────────────┐ │
│ IMPLEMENTATION: TOOL SYMPHONY FREEDOM                       │ │
│ • Scaffolding: Use `kit_stack_list` & `kit_stack_add` to    │ │
│   scaffold stacks in 1 call (never hand-write 15 boilers).  │ │
│ • UI Design: Use `block_palettes` for color tokens and       │ │
│   `block_search` / `block_scaffold` for pre-built blocks.   │ │
│ • Code Invariant: Max 250 lines per file. Never write       │ │
│   monolithic files. Separate HTML, CSS, and JS cleanly.     │ │
│ • Testing & Verification: Start servers with `minitask`,    │ │
│   inspect with `browser_navigate`, run tests with `exec_cmd`│ │
│ • Teardown: Stop dev servers with `minitask(action="stop")`.│ │
└─────────────────────────────────────────────────────────────┘ │

# Universal Tool Capability & Schema Quick Reference:
Below is the definitive reference for minicode's native tools, their schemas, and exact parameters:

1. **Human-in-the-Loop Inquiry (`ask_user`)**:
   - `ask_user(title: str, description: str, questions: list)`
   - Each question object: `{ "id": str, "question": str, "header": str, "input_type": "choice"|"text"|"secret", "is_multi_select": bool, "options": [{"id": str, "label": str, "description": str, "recommended": bool}], "default_value": str }`
   - Example invocation:
     `ask_user(title="Project Architecture & Configuration", description="Confirm preferred stack, styling, and architectural constraints", questions=[{"id": "stack", "question": "Which technology stack would you prefer?", "header": "Stack", "input_type": "choice", "options": [{"label": "Modern Frontend (TypeScript + Tailwind)", "recommended": true}, {"label": "Fullstack Application (FastAPI + React)"}, {"label": "Minimal Lightweight (HTML5 + Modular CSS/JS)"}]}, {"id": "style", "question": "Which visual design theme?", "header": "Theme", "input_type": "choice", "options": [{"label": "Dark Modern Minimal", "recommended": true}, {"label": "Clean High-Contrast Light"}]}])`

2. **MiniKit Architecture & Dependency Tools**:
   - `kit_stack_list(category: optional str)`: Lists available starter stacks (react-vite-gsap, static-website, next-template, fastapi, hono-api, rust-cli, etc.).
   - `kit_stack_add(stack_name: str, target_dir: optional str, no_install: optional bool)`: Scaffolds a full application template with dependencies in 1 call. Also supports remote GitHub repos (e.g. `gh:owner/repo`).
   - `kit_stack_show(stack_name: str)`: Inspects files and dependencies of a stack template without scaffolding.
   - `kit_stack_diff(stack_name: optional str, apply: optional bool)`: Inspects architectural drift between workspace and stack template; repairs missing files when `apply=true`.
   - `kit_info(name: str)`: Fetches package metadata, version, license, and repository across npm, PyPI, crates.io, or pub.dev.
   - `kit_add(name: str, is_dev: optional bool)`: Adds package to project manifest (`package.json`, `Cargo.toml`, etc.) and installs dependencies cleanly.
   - `kit_remove(name: str)`: Removes package from manifest and uninstalls.
   - `kit_sync(manifest_path: optional str, fix_drift: optional bool)`: Reconciles package manifest with lockfiles.
   - `kit_skill_list`: Lists available technology skills.
   - `kit_skill_show(skill_name: str)`: Reads complete guidelines for React, Next.js, Tailwind, Rust, Frontend Design, etc.
   - `kit_skill_install(skill_name: str)`: Installs skill into project `.minicode/skills/` and activates it.

3. **MiniBlocks UI Component & Design Token Warehouse**:
   - `block_palettes(query: optional str, limit: optional int)`: Browse 105+ verified color palette tokens (Background, Surface, Accent, Text).
   - `block_search(query: str, category: optional str, framework: optional str)`: Search 1,080+ pre-built components (heroes, navbars, bento grids, pricing tables, footers, buttons, cards).
   - `block_get(id: str)`: Retrieve complete component source code, palette tokens, or layout template by UUID or name.
   - `block_insert(component_name: str, target_file: str, export_mode: optional str)`: Surgically insert component into target file.
   - `block_scaffold(component_name: str, target_dir: optional str, palette: optional str, wire_to: optional str)`: Scaffolds themed component files pre-wired with design tokens.
   - `block_import(component_name: str, consumer_file: str, wire: optional bool)`: Injects component import statement without rewriting parent files.

4. **Task Planning & Live Progress Tracking**:
   - `create_plan(tasks: list)`: Initialize structured task list. Each task: `{"title": str, "description": str, "verification_command": str}`.
   - `update_progress(step: str, status: "completed"|"in_progress"|"failed"|"pending")`: Update step status (`step="1"`, step title, or `step="active"`). Synchronizes the live TUI execution plan!

5. **MiniTask Process Vault & Dev Servers**:
   - `minitask(action="start", command="...", port=...)`: Launch background dev server or daemon with process group supervision and watchdog.
   - `minitask(action="status"|"resources"|"logs"|"list")`: Inspect running processes, CPU/RAM telemetry, or service logs. NEVER use raw `ps`, `top`, or `grep`!
   - `minitask(action="stop", id="...")` or `minitask(action="kill_all")`: Terminate running servers cleanly.

6. **Web Search & Browser Automation**:
   - `search_web(query: str)`: Search the web with live grounding.
   - `fetch_or_browse(url: str)`: Read static web page or API response.
   - `browser_navigate(url: str, headless: optional bool)`: Launch browser session to inspect rendered UI.
   - `browser_snapshot(annotated: optional bool)`: Capture DOM tree, accessibility nodes, and screenshot.
   - `browser_click(selector: str)` / `browser_type(selector: str, text: str)` / `browser_scroll(direction: str)`: Interact with browser page.
   - `browser_close`: Close active browser window. Always close browser when inspection finishes!

7. **MiniPower Methodology & Verification Barrier**:
   - `power_status`: Check active anti-rationalization guardrails and methodology rules.
   - `power_brainstorm(topic: str)`: Socratic design and trade-off exploration.
   - `power_plan(topic: str, save_to_docs: optional bool)`: Author structured architecture plan in docs/core/todo.md.
   - `power_verify`: Execute the programmatic 4-Gate Pre-Completion Verification Barrier (Gate 1: Compiler & Syntax, Gate 2: Tests, Gate 3: Integrity, Gate 4: Secret Leak Prevention).
   - `power_review`: Two-stage adversarial multi-agent code review.

8. **AST CodeGraph & Symbol Intelligence**:
   - `code_explain(symbol: str)`: Dense AST slice (~150-300 tokens) with signatures, doc comments, callers, and callees.
   - `code_trace(entrypoint: str)`: Downstream call hierarchy and execution flow.
   - `code_impact(target: str)`: Architectural blast radius, affected files, and test suites.

9. **MiniVault Multi-Tier Skills**:
   - `vault_search(query: str)`: Search 30+ built-in, global, and project skills.
   - `vault_show(name: str)`: Read detailed skill instructions and compiler traps.
   - `vault_load(name: str)`: Activate skill into current project `.minicode/skills/`.
   - `vault_import_url(url: str)`: Ingest online skill or guide into project vault.

# Self-Healing & Error Recovery Protocol (Hermes & Oh My Pi):
When a tool returns an error or fails, DO NOT PANIC or repeat the same failing action. Apply these deterministic self-healing steps:
1. **If Error is `Invalid JSON syntax generated by model: EOF while parsing a string`**:
   - *Cause*: The model generated too much output in a single tool call, exceeding token limits and truncating the JSON string.
   - *Fix*: NEVER try to write the same giant file again! Decompose the project into smaller modular files (<200 lines each). Create the skeleton first with `write_file`, then add functions/styles with `patch_file` or write separate `.css` and `.js` modules.
2. **If Error is `patch_file: search block not found`**:
   - *Cause*: Indentation, whitespace, or lines in `search_block` did not match the file on disk.
   - *Fix*: Call `read_file(path, offset=..., limit=...)` to inspect the exact line numbers and indentation. Copy 2-3 lines of surrounding context verbatim.
3. **If Error is `Component not found` or `block_search` returns 0**:
   - *Cause*: Search keywords were too specific or framework filter was overly restrictive.
   - *Fix*: Simplify the query (e.g. search "hero" or "pricing" instead of full sentences). Query `block_palettes` to pick color tokens, or inspect `block_stats` to see available categories.
4. **If Error is `exec_cmd` build or test failure (non-zero exit code)**:
   - *Cause*: Compiler type error, syntax bug, or failing test assertion.
   - *Fix*: Read the exact line number from the compiler/test error in stdout/stderr. Inspect the line with `read_file` or `locate_symbol`. Fix the root cause with `patch_file`. Re-run the test to verify green.
5. **If Error is `ask_user requires at least one question in the 'questions' array`**:
   - *Cause*: Malformed `ask_user` call.
   - *Fix*: Supply `title`, `description`, and a non-empty `questions` array containing structured question objects with `id`, `question`, and `options`.

# Interactive User Clarification & Structured Inquiry (`ask_user`):
<interactive_inquiry>
When a user prompt or task is broad, underspecified, or has multiple viable architectures, stacks, frameworks, themes, or design patterns (e.g. "make a website", "add auth", "create a dashboard"), or when configuration credentials (API keys, connection strings, auth tokens) are needed:
NEVER GUESS, assume, or waste turn cycles hallucinating requirements!
Call the `ask_user` tool immediately. Provide a clear title, description, and structured questions with recommended choices and optional custom write-ins. Minicode will present an interactive inquiry dialog to the user and resume with their explicit choices.
</interactive_inquiry>
"#;

/// Strips thought/reasoning tags and their inner content from text before saving to LLM context history.
#[must_use]
pub fn strip_thought_blocks(raw: &str) -> String {
    let tag_pairs = [
        ("<thought>", "</thought>"),
        ("<think>", "</think>"),
        ("<thinking>", "</thinking>"),
        ("<reasoning>", "</reasoning>"),
        ("<antThinking>", "</antThinking>"),
        ("<Thought>", "</Thought>"),
        ("<Thinking>", "</Thinking>"),
        ("<minimax:tool_call>", "</minimax:tool_call>"),
        ("<tool_call>", "</tool_call>"),
        ("<tool_use>", "</tool_use>"),
        ("<THINK>", "</THINK>"),
    ];

    let mut result = raw.to_string();
    for (open, close) in tag_pairs {
        while let Some(start) = result.find(open) {
            if let Some(end) = result[start..].find(close) {
                let full_end = start + end + close.len();
                result.replace_range(start..full_end, "");
            } else {
                // Unclosed tag: strip to end
                result.truncate(start);
                break;
            }
        }
    }
    result.trim().to_string()
}

/// Sanitizes past user messages by stripping stale <workspace_context> snapshots and unwrapping <user_request>.
#[allow(dead_code)]
#[must_use]
pub fn sanitize_past_user_message(content: &str) -> String {
    // If the message has <user_request>...</user_request>, extract it directly
    if let (Some(start), Some(end)) = (
        content.find("<user_request>"),
        content.rfind("</user_request>"),
    ) {
        if start < end {
            let inner = &content[start + "<user_request>".len()..end];
            return inner.trim().to_string();
        }
    }

    // Otherwise, handle legacy format where <workspace_context> was appended
    let mut cleaned = content.to_string();
    if let Some(start) = cleaned.find("<workspace_context>") {
        if let Some(end) = cleaned[start..].find("</workspace_context>") {
            let full_end = start + end + "</workspace_context>".len();
            cleaned.replace_range(start..full_end, "");
        } else {
            cleaned.truncate(start);
        }
    }
    cleaned.trim().to_string()
}

/// Formats unread peer messages into a structured XML block for turn-start context injection.
#[must_use]
pub fn format_peer_messages_prompt(messages: &[crate::agent::swarm::bus::SwarmMessage]) -> String {
    if messages.is_empty() {
        return String::new();
    }

    let mut out =
        String::from("\n<peer_messages>\n### INCOMING PEER WORKER COORDINATION MESSAGES:\n");
    for msg in messages {
        out.push_str(&msg.format_for_prompt());
        out.push('\n');
    }
    out.push_str("</peer_messages>\n");
    out
}

#[allow(dead_code)]
pub const DEFAULT_SYSTEM_PROMPT: &str = STATIC_SYSTEM_PROMPT;

pub struct PromptBuilder;

impl PromptBuilder {
    /// Assembles the 100% static, cache-friendly system prompt.
    /// This prompt is immutable across turns for maximum prefix caching hits.
    #[must_use]
    pub fn build_static_system_prompt(
        workspace_dir: &Path,
        custom_instructions: Option<&str>,
    ) -> String {
        let mut prompt = String::from(STATIC_SYSTEM_PROMPT);

        prompt.push_str(&format!(
            "\n# Current Workspace:\n{}\n",
            workspace_dir.display()
        ));

        // Inject AGENTS.md rules if present in the workspace
        let agents_file = workspace_dir.join(AGENTS_MD_FILE);
        match std::fs::read_to_string(&agents_file) {
            Ok(content) => {
                let trimmed = if content.len() > MAX_AGENTS_MD_BYTES {
                    tracing::warn!(
                        size = content.len(),
                        max = MAX_AGENTS_MD_BYTES,
                        "AGENTS.md exceeds size limit; truncating"
                    );
                    let valid_end = content.floor_char_boundary(MAX_AGENTS_MD_BYTES);
                    &content[..valid_end]
                } else {
                    &content
                };
                prompt.push_str("\n# Repository Guidelines (AGENTS.md):\n");
                prompt.push_str(trimmed);
                prompt.push('\n');
            }
            Err(e) => {
                if e.kind() != ErrorKind::NotFound {
                    tracing::warn!(path = %agents_file.display(), error = %e, "Failed to read AGENTS.md");
                }
            }
        }

        // Progressive Agent Skills (Tier 1 index + Tier 2 auto-activation based on active workspace/files)
        let progressive_skills =
            crate::tools::minikit::skills::MiniKitSkillsManager::format_progressive_prompt_context(
                workspace_dir,
                &[],
            );
        if !progressive_skills.is_empty() {
            prompt.push_str(&progressive_skills);
        }

        // MiniVault Active Project Skills
        let vault_store = crate::vault::store::VaultStore::new(workspace_dir);
        let all_vault_skills = vault_store.list_all_skills();
        let active_project_skills: Vec<_> = all_vault_skills
            .iter()
            .filter(|s| s.is_active_in_project)
            .collect();

        if !active_project_skills.is_empty() {
            prompt.push_str("\n# Active MiniVault Project Skills:\n");
            prompt.push_str("The following domain skills are actively loaded in this project. Adhere strictly to their guidelines:\n\n");
            for skill in active_project_skills {
                prompt.push_str(&format!(
                    "## Skill `{}`\n_{}_\n\n{}\n\n",
                    skill.name, skill.description, skill.instructions
                ));
            }
        }

        // Append custom user/turn instructions if provided
        if let Some(custom) = custom_instructions {
            prompt.push_str("\n# Additional Instructions:\n");
            prompt.push_str(custom);
            prompt.push('\n');
        }

        // MiniBlocks Native UI Component & Design Warehouse Blueprint
        let stack_info = crate::blocks::seed::ProjectStackInfo::detect(workspace_dir);
        let stack_directive = stack_info.format_prompt_directive();

        prompt.push_str(&format!(
            "\n  <miniblocks_warehouse>\n\
    Native UI warehouse: 1,080+ components, 105 palettes, 212 gradients, 3 templates.\n\
    Tools: `block_search`, `block_get`, `block_insert`, `block_palettes`, `block_gradients`, `block_scaffold`, `block_import`.\n\
    {}\n\
    Workflow Rules:\n\
    1. Query MiniBlocks (`block_search`, `block_palettes`) before creating UI components or color palettes from scratch.\n\
    2. Themed Scaffolding: When choosing a palette from `block_palettes`, pass its name or ID to `block_scaffold(palette=\"...\")` to generate components pre-themed with design tokens (or use `theme-*` / `palette.*` Tailwind classes).\n\
    3. Auto-Wiring: When creating components for an existing parent (like `App.tsx`), pass `wire_to=\"src/App.tsx\"` (or `wire=...`) to `block_scaffold`, or call `block_import(component_name=..., consumer_file=\"src/App.tsx\", wire=true)` for surgical import injection without rewriting parent files.\n\
    4. TypeScript & Vite Conventions: For Vite + React TypeScript projects, ensure `src/vite-env.d.ts` (`/// <reference types=\"vite/client\" />`) and `types: [\"vite/client\"]` in `tsconfig.json` so CSS (`import './index.css'`) and asset imports type-check cleanly.\n\
  </miniblocks_warehouse>\n",
            stack_directive.trim()
        ));

        prompt
    }

    /// Builds the dynamic Zone 3 (Recency Zone) context injected into the conversation tail.
    /// Contains turn-varying state: git status, active working set, memory anchor, progressive memory, and context budget.
    #[must_use]
    pub fn build_recency_context(
        workspace_dir: &Path,
        memory_anchor: Option<&str>,
        active_working_set: &[String],
        git_status: Option<&crate::git::GitStatus>,
        context_budget: Option<&crate::context::budget::ContextBudget>,
        intent_ledger: Option<&crate::context::memory::intent::IntentLedger>,
        workflow_enrichment: Option<&str>,
    ) -> String {
        let mut recency = String::new();
        recency.push_str("\n\n<workspace_context>\n");

        // === ZONE A: KV-CACHE STABLE PREFIX (Ordered by lowest volatility) ===
        // Modern inference runtimes (vLLM, SGLang, LMCache, DeepSeek, Anthropic) utilize
        // radix-tree prefix caching. Placing static or slowly-evolving blocks at the front
        // maximizes cache hits across turns.

        // 1. Scoped DOX Developer Rules (hierarchical AGENTS.md with dynamic headroom scaling)
        let scoped_rules =
            crate::context::governance::dox::DoxEngine::resolve_scoped_rules_with_headroom(
                workspace_dir,
                active_working_set,
                context_budget,
            );
        if !scoped_rules.is_empty() {
            recency.push_str("  <scoped_developer_rules>\n");
            recency.push_str(scoped_rules.trim());
            recency.push_str("\n  </scoped_developer_rules>\n");
        }

        // 2. Progressive 4-Tier Memory (<progressive_memory>)
        let mut prog_memory =
            crate::context::progressive_memory::ProgressiveMemory::load(workspace_dir);
        // Sync any legacy CoreMemory entries into ProgressiveMemory
        let core_memory = crate::context::memory::CoreMemory::load(workspace_dir);
        for g in &core_memory.global_entries {
            prog_memory.add_l3_preference(&g.key, &g.value, "core_memory");
        }
        for l in &core_memory.local_entries {
            prog_memory.add_l2_fact(&l.key, &l.value, "core_memory", 1.0);
        }
        // Apply biological decay retention filter
        prog_memory.prune_decayed(0.15);

        let prog_block = prog_memory.to_prompt_block();
        if !prog_block.is_empty() {
            // Note: prog_block already wraps itself in <progressive_memory> tags
            recency.push_str("  ");
            recency.push_str(prog_block.trim());
            recency.push('\n');
        }

        // 3. Active Working Memory (<task_working_memory>)
        let working_memory = crate::context::working_memory::WorkingMemory::new(workspace_dir);
        let wm_block = working_memory.to_prompt_block();
        if !wm_block.is_empty() {
            recency.push_str("  <task_working_memory>\n");
            recency.push_str(wm_block.trim());
            recency.push_str("\n  </task_working_memory>\n");
        }

        // 4. Active Working Set (recently read / modified files)
        if !active_working_set.is_empty() {
            recency.push_str("  <active_working_set>\n");
            for path in active_working_set.iter().take(8) {
                recency.push_str(&format!("    <file path=\"{}\" />\n", path));
            }
            recency.push_str("  </active_working_set>\n");
        }

        // 5. Living Execution Ledger & Goal Anchor (<goal_anchor>, <execution_ledger>)
        if let Some(ledger) = intent_ledger {
            let ledger_block = ledger.to_prompt_block();
            if !ledger_block.trim().is_empty() {
                recency.push_str(&ledger_block);
            }
        }

        // 6. Verified Active Architectural Invariants (Bi-Temporal Memory)
        let temp_mem =
            crate::context::temporal_memory::TemporalMemoryStore::load_or_default(workspace_dir);
        let temp_mem_block = temp_mem.format_active_context();
        if !temp_mem_block.is_empty() {
            recency.push_str("  ");
            recency.push_str(temp_mem_block.trim());
            recency.push('\n');
        }

        // 7. Recent Architectural Decisions Provenance
        let recent_decisions =
            crate::context::decision_record::DecisionLogger::format_recent_for_context(
                workspace_dir,
                5,
            );
        if !recent_decisions.is_empty() {
            recency.push_str("  ");
            recency.push_str(recent_decisions.trim());
            recency.push('\n');
        }

        // === KV-CACHE ANCHOR DELIMITER ===
        // Delimits invariant/slowly-evolving context from volatile turn-by-turn state
        recency.push_str("  <!-- KV_CACHE_ANCHOR -->\n");

        // === ZONE B: VOLATILE PER-TURN STATE ===

        // 6. Active Workspace Transaction (if one is open)
        if let Ok(Some(active_tx)) =
            crate::session::transaction::TransactionManager::get_active(workspace_dir)
        {
            recency.push_str(&format!(
                "  <active_transaction id=\"{}\" files_tracked=\"{}\">\n    <description>{}</description>\n  </active_transaction>\n",
                active_tx.tx_id,
                active_tx.files.len(),
                active_tx.description
            ));
        }

        // 7. Git Status & Active Branch
        if let Some(status) = git_status {
            recency.push_str(&format!(
                "  <git_status branch=\"{}\" clean=\"{}\">\n",
                status.branch, status.is_clean
            ));
            if !status.staged.is_empty() {
                recency.push_str("    <staged_files>\n");
                for f in status.staged.iter().take(10) {
                    recency.push_str(&format!("      <file path=\"{}\" />\n", f));
                }
                recency.push_str("    </staged_files>\n");
            }
            if !status.unstaged.is_empty() {
                recency.push_str("    <modified_files>\n");
                for f in status.unstaged.iter().take(10) {
                    recency.push_str(&format!("      <file path=\"{}\" />\n", f));
                }
                recency.push_str("    </modified_files>\n");
            }
            if !status.untracked.is_empty() {
                recency.push_str("    <untracked_files>\n");
                for f in status.untracked.iter().take(10) {
                    recency.push_str(&format!("      <file path=\"{}\" />\n", f));
                }
                recency.push_str("    </untracked_files>\n");
            }
            if !status.conflicted.is_empty() {
                recency.push_str("    <conflicted_files>\n");
                for f in &status.conflicted {
                    recency.push_str(&format!("      <file path=\"{}\" />\n", f));
                }
                recency.push_str("    </conflicted_files>\n");
            }
            recency.push_str("  </git_status>\n");
        }

        // 8. MiniPower Verification Barrier Reminder (if modifications exist)
        let has_modified_files = git_status
            .as_ref()
            .map(|s| !s.staged.is_empty() || !s.unstaged.is_empty())
            .unwrap_or(false);
        if has_modified_files {
            recency.push_str("  <minipower_verification_barrier>\n");
            recency.push_str("    Notice: Uncommitted changes detected in working tree. Before completing this task, you MUST run `power_verify` (or compile checks & tests via `exec_cmd`) to satisfy the 4-Gate Pre-Completion Verification Barrier. Evidence before assertions always.\n");
            recency.push_str("  </minipower_verification_barrier>\n");
        }

        // 9. Active Background Tasks & Services (MiniTask Manager & Live Browser)
        let (active_task_count, total_rss_mb, avg_cpu) =
            crate::dev::registry::get_global_dev_registry().get_telemetry_snapshot();
        let browser_live = crate::tools::browser::BrowserManager::is_live_engine_running_sync();
        if active_task_count > 0 || browser_live {
            recency.push_str("  <active_background_tasks>\n");
            recency.push_str(&format!(
                "    Status: {} background task(s) supervised under MiniTask Manager (Total RAM: {:.1}MB, CPU: {:.1}%)\n",
                active_task_count, total_rss_mb, avg_cpu
            ));
            if browser_live {
                recency.push_str("    Browser: Live browser session is running.\n");
            }
            recency.push_str("    Task Management Rules:\n");
            recency.push_str("    • To inspect telemetry or resource usage: ALWAYS call `minitask(action=\"resources\")` or `minitask(action=\"status\")`. NEVER run raw shell commands like `ps`, `top`, or `grep`.\n");
            recency.push_str("    • To stop tasks or servers: ALWAYS call `minitask(action=\"stop\", id=\"...\")` or `minitask(action=\"kill_all\")`. If stopping a web server or web page, ALWAYS also call `browser_close` to terminate the browser window. NEVER run raw `pkill` or `kill` commands.\n");
            recency.push_str("  </active_background_tasks>\n");
        }

        // 9. Project Blueprint Index (Core Specs in core/ available for on-demand inspection via read_file)
        let core_dir = crate::tools::minikit::resolve_core_docs_dir(workspace_dir);
        if core_dir.exists() {
            let mut available_specs = Vec::new();
            for spec_file in crate::tools::minikit::CORE_DOC_FILES {
                if core_dir.join(spec_file).exists() {
                    available_specs.push(*spec_file);
                }
            }
            if !available_specs.is_empty() {
                recency.push_str("  <project_blueprint>\n");
                let rel_core = core_dir.strip_prefix(workspace_dir).unwrap_or(&core_dir);
                recency.push_str(&format!(
                    "    Location: {}/ (Inspect on-demand via `read_file`)\n",
                    rel_core.display()
                ));
                recency.push_str(&format!("    Specs: {}\n", available_specs.join(", ")));
                recency.push_str("  </project_blueprint>\n");
            }
        } else if Self::is_empty_workspace(workspace_dir) {
            // Fresh or empty workspace: Guide the agent appropriately
            recency.push_str("  <project_bootstrap_guidance>\n");
            recency.push_str("    Notice: Workspace is currently empty.\n");
            recency.push_str("    Guidance: If the user provides a greeting, respond naturally and helpfully. If they request building an application or feature, clarify requirements with `ask_user`, choose a stack with `kit_stack_add`, and structure tasks with `create_plan`.\n");
            recency.push_str("  </project_bootstrap_guidance>\n");
        }

        // 10. Active MiniPower Plan & Pending Tasks (from core/todo.md or legacy todo.md)
        let resolved_todo = crate::tools::minikit::resolve_doc_path(workspace_dir, "todo.md");
        let docs_dir = crate::tools::minikit::resolve_docs_dir(workspace_dir);
        let todo_candidates = [
            resolved_todo,
            docs_dir.join("todo.md"),
            workspace_dir.join("todo.md"),
        ];
        for todo_path in &todo_candidates {
            if todo_path.exists() {
                if let Ok(content) = std::fs::read_to_string(todo_path) {
                    let pending: Vec<&str> = content
                        .lines()
                        .filter(|l| {
                            let trimmed = l.trim();
                            trimmed.starts_with("- [ ]")
                                || trimmed.starts_with("* [ ]")
                                || trimmed.starts_with("- [>]")
                                || trimmed.starts_with("* [>]")
                        })
                        .take(5)
                        .collect();
                    if !pending.is_empty() {
                        recency.push_str("  <minipower_active_plan>\n");
                        let rel_path = todo_path.strip_prefix(workspace_dir).unwrap_or(todo_path);
                        recency.push_str(&format!("    Source: {}\n", rel_path.display()));
                        for task in pending {
                            recency.push_str(&format!("    {}\n", task.trim()));
                        }
                        recency.push_str("  </minipower_active_plan>\n");
                        break;
                    }
                }
            }
        }

        // 10. Dynamic Memory Anchor (active objective, key decisions, blockers)
        if let Some(anchor) = memory_anchor {
            if !anchor.trim().is_empty() {
                recency.push_str("  <task_anchor>\n");
                recency.push_str(anchor.trim());
                recency.push_str("\n  </task_anchor>\n");
            }
        }

        // 9. Context Budget & Headroom Bar (most volatile, placed at tail to avoid invalidating KV prefix)
        if let Some(budget) = context_budget {
            recency.push_str(&budget.to_prompt_block());
        }

        // 10. Intent Course-Correction Drift Warning (<intent_focus>)
        if let Some(drift_warning) = intent_ledger
            .and_then(|l| l.check_drift(crate::constants::DEFAULT_INTENT_DRIFT_WARNING_TURNS))
        {
            recency.push_str("  <intent_focus>\n");
            recency.push_str(&format!("    {}\n", drift_warning.trim()));
            recency.push_str("  </intent_focus>\n");
        }

        // 11. Workflow-Specific Autonomous Guidance & Warehouse Enrichments
        if let Some(enrichment) = workflow_enrichment {
            if !enrichment.trim().is_empty() {
                recency.push_str("  ");
                recency.push_str(enrichment.trim());
                recency.push('\n');
            }
        }

        recency.push_str("</workspace_context>");
        recency
    }

    /// Assembles system prompt with optional custom instructions.
    #[allow(dead_code)]
    #[must_use]
    pub fn build_system_prompt(workspace_dir: &Path, custom_instructions: Option<&str>) -> String {
        Self::build_static_system_prompt(workspace_dir, custom_instructions)
    }

    /// Legacy builder for system prompt with embedded anchor.
    #[allow(dead_code)]
    #[must_use]
    pub fn build_system_prompt_with_anchor(
        workspace_dir: &Path,
        custom_instructions: Option<&str>,
        memory_anchor: Option<&str>,
    ) -> String {
        let mut prompt = Self::build_static_system_prompt(workspace_dir, custom_instructions);

        // Inject Progressive 4-Tier Memory (<progressive_memory>)
        let mut prog_memory =
            crate::context::progressive_memory::ProgressiveMemory::load(workspace_dir);
        let core_memory = crate::context::memory::CoreMemory::load(workspace_dir);
        for g in &core_memory.global_entries {
            prog_memory.add_l3_preference(&g.key, &g.value, "core_memory");
        }
        for l in &core_memory.local_entries {
            prog_memory.add_l2_fact(&l.key, &l.value, "core_memory", 1.0);
        }
        prog_memory.prune_decayed(0.15);

        let prog_block = prog_memory.to_prompt_block();
        if !prog_block.is_empty() {
            prompt.push_str("\n# Progressive Multi-Tier Memory:\n");
            prompt.push_str(&prog_block);
            prompt.push('\n');
        }

        // Inject Active Working Memory (<working_memory>)
        let working_memory = crate::context::working_memory::WorkingMemory::new(workspace_dir);
        let wm_block = working_memory.to_prompt_block();
        if !wm_block.is_empty() {
            prompt.push_str("\n# Task Working Memory:\n");
            prompt.push_str(&wm_block);
            prompt.push('\n');
        }

        // Inject Session Memory Anchor if present
        if let Some(anchor) = memory_anchor {
            if !anchor.trim().is_empty() {
                prompt.push_str(anchor);
                prompt.push('\n');
            }
        }

        prompt
    }

    fn is_empty_workspace(workspace: &Path) -> bool {
        let Ok(entries) = std::fs::read_dir(workspace) else {
            return false;
        };
        for entry in entries.flatten() {
            let name = entry.file_name();
            let name_str = name.to_string_lossy();
            if name_str.starts_with('.') {
                continue;
            }
            return false;
        }
        true
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs::File;
    use std::io::Write;

    #[test]
    fn test_build_system_prompt_default() {
        let temp_dir = std::env::temp_dir();
        let prompt = PromptBuilder::build_system_prompt(&temp_dir, None);
        assert!(prompt.contains("You are minicode"));
        assert!(prompt.contains(&temp_dir.display().to_string()));
        assert!(prompt.contains("<miniblocks_warehouse>"));
        assert!(prompt.contains("Native UI warehouse: 1,080+ components"));
        assert!(prompt.contains("Detected Project Stack:"));
    }

    #[test]
    fn test_build_system_prompt_with_detected_stack_react_tailwind() {
        let temp_dir =
            std::env::temp_dir().join(format!("minicode_stack_test_{}", uuid::Uuid::new_v4()));
        std::fs::create_dir_all(&temp_dir).unwrap();

        let pkg = r#"{
            "name": "portal",
            "dependencies": {
                "react": "^18.2.0",
                "tailwindcss": "^3.4.0"
            }
        }"#;
        std::fs::write(temp_dir.join("package.json"), pkg).unwrap();

        let prompt = PromptBuilder::build_system_prompt(&temp_dir, None);
        assert!(prompt.contains("<miniblocks_warehouse>"));
        assert!(prompt.contains("Detected Project Stack: React with Tailwind CSS."));
        assert!(prompt.contains("framework=\"react\" or framework=\"tailwind\""));

        // Cleanup
        std::fs::remove_dir_all(&temp_dir).ok();
    }

    #[test]
    fn test_build_system_prompt_with_agents_md() {
        let temp_dir = std::env::temp_dir().join(format!("minicode_test_{}", uuid::Uuid::new_v4()));
        std::fs::create_dir_all(&temp_dir).unwrap();

        let agents_path = temp_dir.join("AGENTS.md");
        let mut file = File::create(&agents_path).unwrap();
        writeln!(file, "Rule: Never use unwrap!").unwrap();

        let prompt = PromptBuilder::build_system_prompt(&temp_dir, Some("Focus on speed"));
        assert!(prompt.contains("Rule: Never use unwrap!"));
        assert!(prompt.contains("Focus on speed"));

        // Cleanup
        std::fs::remove_dir_all(&temp_dir).ok();
    }

    #[test]
    fn test_build_static_system_prompt_axioms() {
        let temp_dir = std::env::temp_dir();
        let prompt = PromptBuilder::build_static_system_prompt(&temp_dir, None);
        assert!(prompt.contains("Karpathy Guidelines"));
        assert!(prompt.contains("Ponytail Minimalist Ladder"));
        assert!(prompt.contains("Surgical Search-and-Replace"));
        assert!(prompt.contains("Positive Error Handling"));
        assert!(prompt.contains("<interactive_inquiry>"));
        assert!(prompt.contains("ask_user"));
        // Static prompt should NOT contain dynamic memory tags
        assert!(!prompt.contains("<workspace_context>"));
        assert!(!prompt.contains("<task_anchor>"));
    }

    #[test]
    fn test_build_recency_context_formatting() {
        let temp_dir = std::env::temp_dir();
        let active_set = vec!["src/main.rs".to_string(), "src/agent/loop.rs".to_string()];
        let status = crate::git::GitStatus {
            branch: "feature/prompts".to_string(),
            is_clean: false,
            staged: vec!["src/main.rs".to_string()],
            unstaged: vec!["src/agent/prompt.rs".to_string()],
            untracked: vec!["tests/new_test.rs".to_string()],
            conflicted: vec![],
        };
        let anchor = "Active Goal: Implement Tri-Zone Prompts\nStep 1/3: In progress";
        let budget = crate::context::budget::ContextBudget::new(25_000, 128_000, 45_000);

        let recency = PromptBuilder::build_recency_context(
            &temp_dir,
            Some(anchor),
            &active_set,
            Some(&status),
            Some(&budget),
            None,
            None,
        );

        assert!(recency.contains("<workspace_context>"));
        assert!(recency.contains("<context_budget used=\"25000\" limit=\"128000\""));
        assert!(recency.contains("branch=\"feature/prompts\""));
        assert!(recency.contains("clean=\"false\""));
        assert!(recency.contains("<file path=\"src/main.rs\" />"));
        assert!(recency.contains("<file path=\"src/agent/prompt.rs\" />"));
        assert!(recency.contains("<active_working_set>"));
        assert!(recency.contains("<!-- KV_CACHE_ANCHOR -->"));
        assert!(recency.contains("<task_anchor>"));
        assert!(recency.contains("Implement Tri-Zone Prompts"));
        assert!(recency.contains("</workspace_context>"));

        // Verify KV-cache prefix stability: stable active_working_set precedes volatile context_budget
        let active_set_pos = recency
            .find("<active_working_set>")
            .expect("must contain active_working_set");
        let anchor_marker_pos = recency
            .find("<!-- KV_CACHE_ANCHOR -->")
            .expect("must contain KV_CACHE_ANCHOR");
        let budget_pos = recency
            .find("<context_budget")
            .expect("must contain context_budget");
        assert!(active_set_pos < anchor_marker_pos);
        assert!(anchor_marker_pos < budget_pos);
    }

    #[test]
    fn test_build_recency_context_with_intent_ledger_and_drift() {
        let temp_dir = std::env::temp_dir();
        let mut ledger =
            crate::context::memory::intent::IntentLedger::new("Build AgentBench sandbox");
        let id = ledger.add_item("Dashboard metrics", None, vec![]);
        ledger.set_status(
            &id,
            crate::context::memory::intent::RequirementStatus::InProgress,
        );

        // Without drift
        let recency = PromptBuilder::build_recency_context(
            &temp_dir,
            None,
            &[],
            None,
            None,
            Some(&ledger),
            None,
        );
        assert!(recency.contains("<goal_anchor>"));
        assert!(recency.contains("<root_objective>Build AgentBench sandbox</root_objective>"));
        assert!(recency.contains("<execution_ledger progress=\"0/1 completed\">"));
        assert!(recency.contains("[-] Dashboard metrics"));
        assert!(!recency.contains("<intent_focus>"));

        // With drift
        ledger.consecutive_turns_without_progress = 6;
        let recency_drift = PromptBuilder::build_recency_context(
            &temp_dir,
            None,
            &[],
            None,
            None,
            Some(&ledger),
            None,
        );
        assert!(recency_drift.contains("<intent_focus>"));
        assert!(recency_drift.contains("⚠️ Task Drift Warning"));
        assert!(recency_drift.contains("Dashboard metrics"));

        // Verify order: <goal_anchor> in Zone 1 (before KV_CACHE_ANCHOR), <intent_focus> at tail (after KV_CACHE_ANCHOR)
        let anchor_pos = recency_drift
            .find("<goal_anchor>")
            .expect("must contain goal_anchor");
        let kv_pos = recency_drift
            .find("<!-- KV_CACHE_ANCHOR -->")
            .expect("must contain KV_CACHE_ANCHOR");
        let focus_pos = recency_drift
            .find("<intent_focus>")
            .expect("must contain intent_focus");
        assert!(
            anchor_pos < kv_pos,
            "goal_anchor must be in Zone 1 before KV_CACHE_ANCHOR"
        );
        assert!(
            kv_pos < focus_pos,
            "intent_focus must be at tail after KV_CACHE_ANCHOR"
        );
    }

    #[test]
    fn test_build_recency_context_minipower_barrier_and_plan() {
        let temp_dir = tempfile::tempdir().unwrap();
        let todo_file = temp_dir.path().join("todo.md");
        std::fs::write(
            &todo_file,
            "# Task Tracker\n- [ ] Task 1: Autonomous MiniPower wiring\n- [x] Task 0: Done\n",
        )
        .unwrap();

        let git_status = crate::git::GitStatus {
            branch: "main".to_string(),
            staged: vec!["src/agent/prompt.rs".to_string()],
            unstaged: vec![],
            untracked: vec![],
            conflicted: vec![],
            is_clean: false,
        };

        let recency = PromptBuilder::build_recency_context(
            temp_dir.path(),
            None,
            &[],
            Some(&git_status),
            None,
            None,
            None,
        );

        assert!(recency.contains("<minipower_verification_barrier>"));
        assert!(recency.contains("4-Gate Pre-Completion Verification Barrier"));
        assert!(recency.contains("<minipower_active_plan>"));
        assert!(recency.contains("Task 1: Autonomous MiniPower wiring"));
    }

    #[test]
    fn test_build_recency_context_with_workflow_enrichment() {
        let temp_dir = tempfile::tempdir().unwrap();
        let enrichment =
            "<recommended_miniblocks>\n  • `navbar_simple` (React)\n</recommended_miniblocks>";
        let recency = PromptBuilder::build_recency_context(
            temp_dir.path(),
            None,
            &[],
            None,
            None,
            None,
            Some(enrichment),
        );
        assert!(recency.contains("<workspace_context>"));
        assert!(recency.contains("<recommended_miniblocks>"));
        assert!(recency.contains("`navbar_simple` (React)"));
        assert!(recency.contains("</workspace_context>"));
    }

    #[test]
    fn test_is_empty_workspace_and_bootstrap_guidance() {
        let temp_dir = tempfile::tempdir().unwrap();
        assert!(PromptBuilder::is_empty_workspace(temp_dir.path()));

        // Empty workspace gets project bootstrap guidance
        let recency_empty = PromptBuilder::build_recency_context(
            temp_dir.path(),
            None,
            &[],
            None,
            None,
            None,
            None,
        );
        assert!(recency_empty.contains("<project_bootstrap_guidance>"));

        // Non-empty workspace (e.g., existing code without docs) does NOT get nagged with kit_sync
        std::fs::write(temp_dir.path().join("main.rs"), "fn main() {}").unwrap();
        assert!(!PromptBuilder::is_empty_workspace(temp_dir.path()));

        let recency_non_empty = PromptBuilder::build_recency_context(
            temp_dir.path(),
            None,
            &[],
            None,
            None,
            None,
            None,
        );
        assert!(!recency_non_empty.contains("<project_bootstrap_guidance>"));
    }

    #[test]
    fn test_format_peer_messages_block() {
        let msg = crate::agent::swarm::bus::SwarmMessage::new(
            "swarm-1",
            "t1_api",
            None,
            crate::agent::swarm::bus::SwarmMessageIntent::PublishContract,
            "User Schema",
            "export interface User { id: string; }",
        );
        let block = crate::agent::prompt::format_peer_messages_prompt(&[msg]);
        assert!(block.contains("<peer_messages>"));
        assert!(block.contains("export interface User"));
        assert!(block.contains("</peer_messages>"));

        // Verify empty slice produces empty string
        assert_eq!(crate::agent::prompt::format_peer_messages_prompt(&[]), "");
    }
}
